Repository dcos/dcos, pull requests merged in 2018-08, with the labels that each got.

#3158 Bump dcos-ui to 1.10.9-rc.1
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#3160 Prune owners.json
  owners.json
Labels: Ship It

#3163 1.10: Accessibility to zk is a requirement for Marathon to start
  packages/marathon/build
Labels: Ship It

#3167 Bump the timeout to 10 minutes
  gen/dcos-config.yaml
Labels: Ship It

#3168 Bump the timeout to 10 minutes
  gen/dcos-config.yaml
Labels: Ship It

#3145 Prune owners.json
  owners.json
Labels: Ship It

#3166 Set the timeout to 10 minutes instead of 600 millis
  gen/dcos-config.yaml
Labels: Ship It

#3126 [1.11] Bump dcos-metrics
  CHANGES.md
  packages/dcos-metrics/buildinfo.json
Labels: Ship It

#3146 [1.11] Added a Mesos patch that makes it possible to enable offer logging.
  packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
  packages/mesos/extra/patches/0002-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
  packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch
  packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
  packages/mesos/extra/patches/0005-Displayed-resource-provider-resources-in-GET_RESOURC.patch
  packages/mesos/extra/patches/0006-Improved-logging-for-offers-and-inverse-offers.patch
Labels: Ship It

#3162 1.11: Accessibility to zk is requirement for a marathon start
  packages/marathon/build
Labels: Ship It

#3180 Fix the mesos webui master log view / download links.
  packages/mesos/buildinfo.json
  packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
  packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
  packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
  packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch
Labels: Ship It

#3185 chore(dcos-ui): bump DC/OS UI v2.3.0
  CHANGES.md
  packages/dcos-ui/build
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#3193 locks the glide version to fix build issue with the latest version
  packages/dcos-cni/build
Labels: Ship It

#3159 Prune owners.json
  owners.json
Labels: Ship It

#3225 [1.11] packages/java: Update Java to 8u181 version
  packages/java/buildinfo.json
Labels: Ship It

#3226 [1.10] packages/java: Update Java to 8u181 version
  packages/java/buildinfo.json
Labels: Ship It

#3211 Add information to diagnostics bundle
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#3221 Remove duplicated code in dcos diagnostics test
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#3240 Update owners.json
  owners.json
Labels: Ship It

#3236 [Backport 1.10] Add bootstrap ip-detect check for static backend
  CHANGES.md
  packages/exhibitor/extra/start_exhibitor.py
Labels: Ship It

#3242 Update owners.json
  owners.json
Labels: Ship It

#3252 Marathon Maintenance mode on by default for DCOS
  packages/marathon/extra/marathon.sh
Labels: Ship It

#3253 Fix windows build of mesos package
  packages/mesos/windows.buildinfo.json
Labels: Ship It

#3206 [1.10] Bump navstar
  packages/navstar/buildinfo.json
Labels: Ship It

#3234 [Backport][1.10] locks the glide version to fix build issue
  packages/dcos-cni/build
Labels: Ship It

#3233 [Backport][1.11] locks the glide version to fix build issue
  packages/dcos-cni/build
Labels: Ship It

#3241 Update owners.json
  owners.json
Labels: Ship It

#3248 [1.11] changelog: Add Java update note
  CHANGES.md
Labels: Ship It

#3164 1.9: Accessibility to zk is a requirement for Marathon to start
  packages/marathon/build
Labels: Ship It

#3289 Marathon 1.6.544 bump on DC/OS 1.11
  packages/marathon/buildinfo.json
Labels: Ship It

#3250 Implement bootstrap methods for telegraf
  packages/bootstrap/extra/dcos_internal_utils/cli.py
Labels: Ship It

#3282 test_vip: purge proxy app
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#3290 bump marathon 1.7.81
  packages/marathon/buildinfo.json
Labels: Ship It

#3283 [1.11] test_vip: purge proxy app
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#3284 DC/OS UI: 1.11+v1.18.0
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#3295 chore(dcos-ui): bump DC/OS UI v1.19.0
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#3296 Update DC/OS version to 1.11.5
  dcos_installer/test_backend.py
  gen/calc.py
Labels: Ready For Review

#3243 Update owners.json
  owners.json
Labels: Ship It

#3304 [1.9] Bump Martahon's task_launch_confirm and task_reservation timeouts
  packages/marathon/build
Labels: Ship It

#2014 mom integration test
  packages/dcos-integration-test/extra/test_packaging.py
Labels: Ship It

#3297 Update owners.json
  owners.json
Labels: Ship It

#3301 Bump Martahon's task_launch_confirm and task_reservation timeouts
  packages/marathon/extra/marathon.sh
Labels: Ship It

#3314 Update to Metronome 0.4.4
  packages/metronome/buildinfo.json
Labels: Ship It

#3302 [1.11] Bump Martahon's task_launch_confirm and task_reservation timeouts
  packages/marathon/extra/marathon.sh
Labels: Ship It

#3315 Bump metronome to 0.4.4
  packages/metronome/buildinfo.json
Labels: Ship It

#3327 Update owners.json
  owners.json
Labels: Work In Progress

#3316 Bump Metronome to 0.4.4
  packages/metronome/buildinfo.json
Labels: Ship It

#3324 Update owners.json
  owners.json
Labels: Work In Progress

#3326 Update owners.json
  owners.json
Labels: Work In Progress

#3325 Update owners.json
  owners.json
Labels: Work In Progress

#3334 chore(dcos-ui): bump DC/OS UI 1.11+v1.20.0
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#3330 chore(dcos-ui): bump DC/OS UI 1.9+v1.9.11-rc1
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#3148 Add timestamp for dmesg, distro version, timedatectl and systemd unit status to diag bundle
  CHANGES.md
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#3276 Check cache when creating Mesos resources using make_disk_resources.py.
  packages/mesos/extra/make_disk_resources.py
Labels: Ship It

#3277 Create `marathon_port` variable in config
  gen/calc.py
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_misc.py
Labels: Ship It

#3308 gen/build_deploy/bash: Allow SELinux preflight check to pass on Enfor…
  CHANGES.md
  gen/build_deploy/bash.py
Labels: Ship It

#3337 feat: enable intercom ui plugin
  gen/calc.py
  gen/dcos-config.yaml
Labels: Ship It

#3338 chore(dcos-ui): bump DC/OS UI master+v2.14.0
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#3353 Support custom managers in cosmos
  packages/cosmos/buildinfo.json
Labels: Ship It

#3358 Mergebot config to support fixVersions
  mergebot-config.json
Labels: Ship It

#3360 [1.11.5] Disable a watchdog for stuck processes
  gen/dcos-config.yaml
Labels: Ship It

#3362 Disable a watchdog for stuck processes
  gen/dcos-config.yaml
Labels: Ship It

#3369 chore(dcos-ui): bump DC/OS UI master+v2.18.0
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ship It
