Repository dcos/dcos, pull requests merged in 2019-04, with the labels that each got.

#4947 [master] Automated Bump DC/OS UI v2.71.0
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4929 [1.12] Use configured timeout in http client instead of mesos query param
  CHANGES.md
  packages/telegraf/buildinfo.json
Labels: Ship It

#4928 [1.13] Use configured timeout in http client instead of mesos query param
  packages/telegraf/buildinfo.json
Labels: Ship It

#4939 Telegraf scale tuning
  gen/dcos-config.yaml
Labels: Ship It

#4955 [master] Automated Bump DC/OS UI v2.73.0
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4948 Bump dcos-checks
  packages/dcos-checks/buildinfo.json
Labels: Ship It

#4962 Bump Marathon to 1.8.164 on DC/OS 1.13
  packages/marathon/buildinfo.json
Labels: Ship It

#4968 metronome 0.6.18 bump on dcos 1.11
  packages/metronome/buildinfo.json
Labels: Ship It

#4967 metronome 0.6.18 bump on dcos 1.12
  packages/metronome/buildinfo.json
Labels: Ship It

#4970 unmute test_metronome
  packages/dcos-integration-test/extra/test_metronome.py
Labels: Ship It

#4976 [master] Automated Bump DC/OS UI v2.73.1
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4979 [1.13] Add dcos_fluent_bit user to systemd-journal group
  packages/fluent-bit/buildinfo.json
Labels: Ship It

#4986 [master] Automated Bump DC/OS UI v2.75.0
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4997 Bump marathon to 1.8.172
  packages/marathon/buildinfo.json
Labels: Ship It

#5004 [master] Automated Bump DC/OS UI v2.76.0
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#5015 Update Status Checks Published and Explain about Required vs Non Required
  README.md
Labels: merge-by-mergebot

#5007 Add sysctl to diagnostics bundle
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#4998 Bump dcos-diagnostics and adapt build
  packages/dcos-diagnostics/build
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#5023 Add integration test for checking nginx_service_* Telegraf metrics
  packages/dcos-integration-test/extra/test_metrics.py
Labels: Ship It

#4988 Changed order of containerizers on Mesos agents.
  gen/dcos-config.yaml
Labels: Ship It

#5032 Update DC/OS to track Mesos 1.8.x release branch.
  packages/mesos-modules/buildinfo.json
  packages/mesos/buildinfo.json
  packages/mesos/windows.buildinfo.json
Labels: Ship It

#5026 [master] Automated Bump DC/OS UI v2.77.4
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4987 Bump dcos-signal
  packages/dcos-signal/buildinfo.json
Labels: Ship It

#5033 Bump Marathon to 1.5.15
  packages/marathon/buildinfo.json
Labels: Ship It

#5039 Bump cosmos to latest snapshot
  packages/cosmos/buildinfo.json
Labels: Ship It

#5049 [master] Automated Bump DC/OS UI v2.78.2
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4903 Upgrade OTP version
  packages/erlang/buildinfo.json
Labels: Ship It

#5053 Fix integration test for Telegraf metrics
  packages/dcos-integration-test/extra/test_metrics.py
Labels: Ship It

#5030 Enable continuous-integration/jenkins/pr-head as a required status check
  mergebot-config.json
Labels: Ship It

#5069 Bump dcos-diagnostics
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#5072 Bump metronome on DC/OS 1.13
  packages/metronome/buildinfo.json
Labels: Ship It

#5076 [master] Automated Bump DC/OS UI v2.80.1
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#5082 bumping Marathon 1.8.180 for seccomp
  CHANGES.md
  packages/marathon/buildinfo.json
Labels: Ship It

#5059 [1.12] Bump cosmos to latest version
  packages/cosmos/buildinfo.json
Labels: Ship It

#5084 [master] Automated Bump DC/OS UI v2.81.3
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#5092 [master] Automated Bump DC/OS UI v2.81.4
  packages/dcos-ui/buildinfo.json
Labels: Work In Progress

#5070 dcos-integration-test: skip rexray test in strict mode, unmute it
  packages/dcos-integration-test/extra/test_rexray.py
Labels: Ship It

#5104 Update version to 1.13.0-beta
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
Labels: merge-by-mergebot

#5106 Update Mergebot Config for Master.
  CHANGES.md
  mergebot-config.json
Labels: merge-by-mergebot

#5098 Added vinodkone to owners.json.
  owners.json
Labels: Ship It

#5113 Hide secret keys from user.config.yaml
  gen/calc.py
Labels: Ship It

#5148 [BACKPORT][DCOS-50035] lighter weight image and updated distro for tests
  packages/dcos-integration-test/extra/test_applications.py
  packages/dcos-integration-test/extra/test_helpers.py
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#5146 [BACKPORT][DCOS-50035] Moving to smaller image and updated distro for tests
  packages/dcos-integration-test/extra/test_applications.py
  packages/dcos-integration-test/extra/test_helpers.py
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#5147 [BACKPORT][DCOS-50035] Moving to smaller image and updated distro for tests
  packages/dcos-integration-test/extra/test_applications.py
  packages/dcos-integration-test/extra/test_helpers.py
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#5162 Bump dcos-test-utils
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#5126 Log checks API result before status assertion
  packages/dcos-integration-test/extra/test_checks.py
Labels: Ship It

#5165 Bump dcos-test-utils
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#5132 [1.13] Tune fluent bit's configuration
  gen/dcos-config.yaml
Labels: Ship It

#5170 Add tests for networking commands in diagnostic bundle
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#5143 [BACKPORT][DCOS-50035] lighter weight image and updated distro for tests
  CHANGES.md
  gen/calc.py
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#5131 Tune fluent bit's configuration
  gen/dcos-config.yaml
Labels: Ship It

#5140 Send pre-compressed UI assets if possible.
  CHANGES.md
  packages/adminrouter/extra/src/includes/server/master.conf
  packages/dcos-integration-test/extra/test_adminrouter_open.py
Labels: Ship It

#5168 Bump Marathon to 1.7.216
  CHANGES.md
  packages/marathon/buildinfo.json
Labels: Ship It

#5199 [1.13] Automated Bump DC/OS UI v2.82.0
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#5211 Updated DC/OS version to 1.13.0
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
Labels: Ready For Review

#5214 Update mergebot-config to include DC/OS 1.13.0 and DC/OS 1.13.1
  mergebot-config.json
Labels: Ship It

#5231 NatInstance to reference Default InstanceType.
  gen/aws/templates/cloudformation.json
Labels: Ship It

#5232 DCOS-51332 - NatInstance to reference Default InstanceType.
  gen/aws/templates/cloudformation.json
Labels: Ship It

#5219 DCOS-51332 - NatInstance to reference Default Instance Type.
  gen/aws/templates/cloudformation.json
Labels: Ship It

#5217 Bump dcos-test-utils to pin dcos cli
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#5215 Bump dcos-test-utils to pin dcos cli
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#5212 Bump dcos-test-utils to pin dcos cli
  packages/dcos-integration-test/extra/test_legacy_user_management.py
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#5233 DCOS-51332 - NatInstance to reference Default Instance Type
  gen/aws/templates/cloudformation.json
Labels: Ship It

#5213 Bump dcos-test-utils to pin dcos cli
  packages/dcos-integration-test/extra/test_legacy_user_management.py
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#5198 test-e2e/cluster_helpers: save cluster log files with log extension
  test-e2e/cluster_helpers.py
Labels: Ship It

#5245 [master] Automated Bump DC/OS UI v2.85.0
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#5249 [1.13] test-e2e/cluster_helpers: save cluster log files with log extension
  test-e2e/cluster_helpers.py
Labels: Ship It

#5253 Update exhibitor/buildinfo.json
  packages/exhibitor/buildinfo.json
Labels: Ship It

#5248 [1.11] test-e2e/cluster_helpers: save cluster log files with log extension
  test-e2e/cluster_helpers.py
Labels: Ship It

#5265 Bump dcos-checks
  packages/dcos-checks/buildinfo.json
Labels: Ship It

#5252 Update exhibitor/buildinfo.json
  packages/exhibitor/buildinfo.json
Labels: Ship It

#5250 [1.12] test-e2e/cluster_helpers: save cluster log files with log extension
  test-e2e/cluster_helpers.py
Labels: Ship It

#5183 Switched Mesos to current master.
  packages/mesos/buildinfo.json
  packages/mesos/windows.buildinfo.json
Labels: Ship It

#5281 [1.13] Send pre-compressed UI assets if possible.
  CHANGES.md
  packages/adminrouter/extra/src/includes/server/master.conf
  packages/dcos-integration-test/extra/test_adminrouter_open.py
Labels: Ship It

#5290 [master] Automated Bump DC/OS UI v2.86.1
  packages/dcos-ui/buildinfo.json
Labels: merge-by-mergebot

#5280 [1.13.0] Added mesos patch that reverts ContainerInfo protobuf validation.
  packages/mesos/extra/patches/0006-Revert-Validated-the-match-between-Type-and-Infos-in.patch
Labels: merge-by-mergebot

#5282 Update cache headers to more appropriate values
  packages/adminrouter/extra/src/includes/server/master.conf
  packages/dcos-integration-test/extra/test_adminrouter_open.py
Labels: Ship It

#5285 Use `docker ps` instead of `docker up` in diagnostics
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#5300 Bump dcos-diagnostics
  CHANGES.md
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#5318 [1.13.0] Bump dcos-net
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: merge-by-mergebot

#5286 [1.13] Added mesos patch that reverts ContainerInfo protobuf validation.
  packages/mesos/extra/patches/0006-Revert-Validated-the-match-between-Type-and-Infos-in.patch
Labels: Ship It

#5322 [1.11] Bump dcos-net
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#5292 Bump dcos-net
  packages/dcos-net/buildinfo.json
Labels: Ship It

#5321 [1.12] Bump dcos-net
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#5303 [1.13] Bump dcos-diagnostics
  CHANGES.md
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#5310 Fix syntax error in domain detect script
  gen/fault-domain-detect/cloud.sh
Labels: Ship It

#5308 Fix syntax error in domain detect script
  gen/fault-domain-detect/cloud.sh
Labels: Ship It

#5287 Added mesos patch that reverts ContainerInfo protobuf validation.
  packages/mesos/extra/patches/0006-Revert-Validated-the-match-between-Type-and-Infos-in.patch
Labels: Ship It

#5311 Fix syntax error in domain detect script
  gen/fault-domain-detect/cloud.sh
Labels: Ship It

#5336 DCOS_OSS-4097 - Explicitly create user groups in pkgpanda
  pkgpanda/__init__.py
Labels: Ship It

#5344 DCOS-52191 - Mute flaky test test_dcos_diagnostics_bundle_create_download_delete
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: merge-by-mergebot

#5309 Fix syntax error in domain detect script
  gen/fault-domain-detect/cloud.sh
Labels: Ship It

#5320 [1.13] Bump dcos-net
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#5332 Fixed changelog entry for dcos-diagnostics changes
  CHANGES.md
Labels: Ship It

#5347 CHANGES.md: editorial update for 1.14.0 development
  CHANGES.md
Labels: merge-by-mergebot

#5348 CHANGES.md: editorial update for 1.13.1 development
  CHANGES.md
Labels: merge-by-mergebot

#5349 CHANGES.md: editorial update for 1.12 development
  CHANGES.md
Labels: merge-by-mergebot

#5363 CHANGES.md: editorial update for 1.10 branch
  CHANGES.md
Labels: merge-by-mergebot

#5369 CHANGES.md: another editorial overhaul for 1.10
  CHANGES.md
Labels: merge-by-mergebot

#5355 DCOS-51350 - adding ELB permissions to cloudformation templates
  gen/aws/templates/cloudformation.json
Labels: merge-by-mergebot
