Repository dcos/dcos, pull requests merged in 2019-09, with the labels that each got.

#6204 DC/OS version 2.0.0-beta.
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
Labels: Ready For Review

#6205 Set Branch Protections for 2.0 Branch.
  mergebot-config.json
Labels: merge-by-mergebot

#6197 [1.12] Bump dcos-diagnostics version
  CHANGES.md
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#6196 [1.13] Bump dcos-diagnostics version
  CHANGES.md
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#6161 [master] Bump Mesos to 1.9.0-rc3
  CHANGES.md
  packages/mesos/buildinfo.json
  packages/mesos/windows.buildinfo.json
Labels: Ship It

#6209 Add myself to owners file and remove Adam
  owners.json
Labels: Ship It

#6220 Set JIRA fix Version to DC/OS 1.14.0
  mergebot-config.json
Labels: Ship It

#6218 Backport Exhibitor TLS client changes 1.12
  packages/dcos-diagnostics/extra/dcos-diagnostics-master.service
Labels: Ship It

#6221 Collect all lines for mesos node logs
  fetch_cluster_logs.bash
Labels: merge-by-mergebot

#6224 Bump dcos-diagnostics
  fetch_cluster_logs.bash
Labels: merge-by-mergebot

#6225 [2.0] Bump dcos-diagnostics
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#6227 [1.12] Bump dcos-diagnostics
  packages/dcos-diagnostics/extra/dcos-diagnostics-master.service
Labels: Ship It

#6237 Fix windows build
  pkgpanda/util.py
Labels: merge-by-mergebot

#6241 Use dcos-core-cli-2.0-patch.2 in tests
  packages/dcos-integration-test/extra/conftest.py
Labels: Ship It

#6251 [1.12] Bump Mesos modules
  CHANGES.md
  packages/mesos-modules/buildinfo.json
Labels: Ship It

#6249 [2.0] Bump Mesos modules
  CHANGES.md
  packages/mesos-modules/buildinfo.json
Labels: Ship It

#6248 Bump Mesos modules
  CHANGES.md
  packages/mesos-modules/buildinfo.json
Labels: Ship It

#6211 Oracle JDK -> Open JDK
  CHANGES.md
  packages/java/build
  packages/java/buildinfo.json
Labels: merge-by-mergebot

#6250 [1.13] Bump Mesos modules
  CHANGES.md
  packages/mesos-modules/buildinfo.json
Labels: Ship It

#6265 Set the 1.13 in-development version to 1.13.6
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
Labels: merge-by-mergebot

#6234 Add marathon_new_group_enforce_role config option to the DC/OS installer
  CHANGES.md
  gen/calc.py
  gen/dcos-config.yaml
Labels: Ship It

#6277 [1.11] Remove nogroup group creation
  CHANGES.md
  cloud_images/lib/el7/configure_dcos_system.sh
  gen/build_deploy/bash.py
Labels: Ship It

#6276 [1.12] Remove nogroup group creation
  CHANGES.md
  cloud_images/lib/el7/configure_dcos_system.sh
  gen/build_deploy/bash.py
Labels: Ship It

#6275 [1.13] Remove nogroup group creation
  CHANGES.md
  cloud_images/lib/el7/configure_dcos_system.sh
  gen/build_deploy/bash.py
Labels: Ship It

#6273 Oracle Java -> OpenJDK
  CHANGES.md
  packages/java/build
  packages/java/buildinfo.json
Labels: Ship It

#6264 Removed Fixed and Improved section as per changelog protocol.
  CHANGES.md
Labels: merge-by-mergebot

#6296 CHANGES.md: editorial update for 1.13 branch, towards 1.13.5 release
  CHANGES.md
Labels: merge-by-mergebot

#6278 Update owners.json
  owners.json
Labels: Ship It

#6268 [2.0] Bump DC/OS Net
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#6267 Bump DC/OS Net
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#6253 Windows builds are required by now.
  mergebot-config.json
Labels: Ship It

#6290 Unmute test_if_overlay_ok
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#6291 Unmute test_if_overlay_ok
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#6303 Updated Windows build script.
  packages/mesos/windows.build.ps1
Labels: Ship It

#6308 Remove spartan
  CHANGES.md
  NOTICE
  packages/installer.treeinfo.json
  packages/spartan/extra/dcos-gen-resolvconf.service
  packages/spartan/extra/dcos-gen-resolvconf.timer
  packages/spartan/extra/dcos-spartan-watchdog.service
  packages/spartan/extra/dcos-spartan-watchdog.timer
  packages/spartan/extra/dcos-spartan.service
  packages/spartan/extra/gen_resolvconf.py
  packages/spartan/extra/spartan-service.xml
  packages/spartan/extra/sys.spartan.config
  packages/spartan/extra/vm.spartan.args
  packages/spartan/windows.build.ps1
  packages/spartan/windows.buildinfo.json
  packages/treeinfo.json
  packages/windows.treeinfo.json
Labels: merge-by-mergebot

#6187 Bumped dcos-test-utils to include new test helpers.
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#6283 Add marathon_new_group_enforce_role config option to the DC/OS installer
  CHANGES.md
  gen/calc.py
  gen/dcos-config.yaml
Labels: Ship It

#6314 Update fix version 1.11.13
  mergebot-config.json
Labels: Ship It

#6313 1.11.12-dev -> 1.11.13-dev
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
Labels: Ship It

#6318 [Master] Bump Mesos to include SSL environment variable renamings.
  CHANGES.md
  packages/mesos/buildinfo.json
Labels: merge-by-mergebot

#6287 [2.0] Bump Mesos to include SSL environment variable renamings.
  CHANGES.md
  packages/mesos/buildinfo.json
Labels: Ship It

#6324 Remove the toybox package
  CHANGES.md
  NOTICE
  packages/toybox/build
  packages/toybox/buildinfo.json
  packages/toybox/extra/config
  packages/windows.treeinfo.json
Labels: merge-by-mergebot
