Repository dcos/dcos, pull requests merged in 2019-10, with the labels that each got.

#6331 DCOS_OSS-5579 - Pin attrs dependency for a breaking change.
  packages/adminrouter/docker/requirements-tests.txt
  test-e2e/requirements.txt
  tox.ini
Labels: Ship It

#6332 DCOS_OSS-5579 - Pin attrs dependency for a breaking change.
  packages/adminrouter/docker/requirements-tests.txt
  test-e2e/requirements.txt
  tox.ini
Labels: Ready For Review

#6330 DCOS_OSS-5579 - Pin attrs dependency for a breaking change.
  packages/adminrouter/docker/requirements-tests.txt
  test-e2e/requirements.txt
  tox.ini
Labels: Ready For Review

#6325 Use bridge networking for invalid service port test
  packages/dcos-integration-test/extra/test_adminrouter_open.py
Labels: Ship It

#6333 DCOS_OSS-5579 - Pin attrs dependency for a breaking change.
  packages/adminrouter/docker/requirements-tests.txt
  test-e2e/requirements.txt
  tox.ini
Labels: merge-by-mergebot

#6334 DCOS_OSS-5579 - Pin attrs dependency for a breaking change.
  packages/adminrouter/docker/requirements-tests.txt
  test-e2e/requirements.txt
  tox.ini
Labels: merge-by-mergebot

#6335 DCOS_OSS-5579 - Pin attrs dependency for a breaking change.
  packages/adminrouter/docker/requirements-tests.txt
  test-e2e/requirements.txt
  tox.ini
Labels: merge-by-mergebot

#6336 DCOS_OSS-5579 - Pin attrs dependency for a breaking change.
  packages/adminrouter/docker/requirements-tests.txt
  test-e2e/requirements.txt
  tox.ini
Labels: merge-by-mergebot

#6322 Bump cosmos to latest version
  CHANGES.md
  packages/mesos/buildinfo.json
Labels: Ship It

#6337 Use bridge networking for invalid service port test
  packages/dcos-integration-test/extra/test_adminrouter_open.py
Labels: Ship It

#6327 Use bridge networking for invalid service port test
  packages/dcos-integration-test/extra/test_adminrouter_open.py
Labels: Ship It

#6352 Removing dcos-metrics and using azure for releases.
  build_local_windows.ps1
  config/dcos-release-windows.config.yaml
  packages/dcos-metrics/windows.build.ps1
  packages/dcos-metrics/windows.buildinfo.json
  packages/windows.treeinfo.json
Labels: Ship It

#6365 Update dcos-diagnostics
  packages/dcos-diagnostics/buildinfo.json
Labels: merge-by-mergebot

#6366 [2.0] Update dcos-diagnostics
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#6371 Use correct start arguments for cockroachdb 2.1
  packages/cockroach/extra/cockroach.sh
  packages/cockroach/extra/register.py
Labels: Ship It

#6372 [DCOS 2.0] Use correct start arguments for cockroachdb 2.1
  packages/cockroach/extra/cockroach.sh
  packages/cockroach/extra/register.py
Labels: Ship It

#6376 Update dcos-diagnostics for windows
  packages/dcos-diagnostics/windows.buildinfo.json
Labels: Ship It

#6387 DCOS-57281 unify DC/OS Signal EE and OSS
  CHANGES.md
  packages/dcos-integration-test/extra/test_composition.py
  packages/dcos-integration-test/extra/test_groups.yaml
  packages/dcos-integration-test/extra/test_signal.py
  packages/dcos-signal/build
  packages/dcos-signal/buildinfo.json
  packages/dcos-signal/extra/dcos-signal.service
  packages/dcos-signal/extra/dcos-signal.timer
Labels: Ship It

#6388 [1.12] DCOS-57281 unify DC/OS Signal EE and OSS
  CHANGES.md
  packages/dcos-integration-test/extra/test_composition.py
  packages/dcos-integration-test/extra/test_groups.yaml
  packages/dcos-integration-test/extra/test_signal.py
  packages/dcos-signal/build
  packages/dcos-signal/buildinfo.json
  packages/dcos-signal/extra/dcos-signal.service
  packages/dcos-signal/extra/dcos-signal.timer
Labels: Ship It

#6390 Delete NEWS
  NEWS
Labels: Ship It

#6377 Remove test_util/run-all script
  .gitignore
  test_util/README.md
  test_util/run-all
Labels: Ship It

#6402 Bump dcos-test-utils
  packages/dcos-test-utils/buildinfo.json
Labels: merge-by-mergebot

#6393 chore: Bump DC/OS UI v2.150.0
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#6397 Bump Mesos modules
  packages/mesos-modules/buildinfo.json
Labels: merge-by-mergebot

#6406 [1.13] Bump Mesos modules
  CHANGES.md
  packages/mesos-modules/buildinfo.json
Labels: Ship It

#6414 updating windows GH status to not have hyphen which is known to be dr…
  mergebot-config.json
Labels: Ship It

#6426 Update mergebot fix version config to 1.15.0
  README.md
Labels: merge-by-mergebot

#6438 Update the mergebot fix version for 2.0 branch.
  mergebot-config.json
Labels: merge-by-mergebot

#6439 Update version and change.md for 2.0.1
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
Labels: merge-by-mergebot

#6449 Add retry mechanism to AWS ip-detect scripts
  gen/ip-detect/aws.sh
  gen/ip-detect/aws6.sh
  gen/ip-detect/aws_public.sh
Labels: Ship It
