Repository dcos/dcos, pull requests merged in 2019-03, with the labels that each got.

#4617 [BACKPORT] [1.11] DCOS-46146 - Re-enable test_ipv6 and test_if_overlay_ok
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#4609 bumping metronome 0.6.11 on dcos 1.12
  packages/metronome/buildinfo.json
Labels: Ship It

#4648 update version to 1.12.3
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
Labels: Work In Progress

#4649 update mergebot config for next version of DC/OS 1.12
  mergebot-config.json
Labels: merge-by-mergebot

#4616 DCOS-46146 - Re-enable test_ipv6 and test_if_overlay_ok
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#4637 [master] Automated Bump DC/OS UI v2.58.0
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4642 Update the cloud-formation templates to use specific Availability Zone
  gen/aws/templates/cloudformation.json
Labels: Ship It

#4651 [1.11] DCOS-46615 - Make pkgpanda resistant to missing content-length
  pkgpanda/test_util.py
  pkgpanda/util.py
Labels: Ship It

#4650 [1.12] DCOS-46615 - Make pkgpanda resistant to missing content-length
  pkgpanda/test_util.py
  pkgpanda/util.py
Labels: Ship It

#4593 Fixed spelling in MD docs
  docs/package_basics.md
  docs/windows.md
  pkgpanda/docs/create_and_maintain_packages.md
  pkgpanda/docs/tree_concepts.md
Labels: Ship It

#4654 bump dcos-check-runner
  packages/dcos-check-runner/buildinfo.json
Labels: Ship It

#4658 Add pid to bootstrap logs to distinguish concurrent runs
  packages/bootstrap/extra/dcos_internal_utils/cli.py
Labels: Ship It

#4643 Updating invocation of pip upgrade to remove error message.
  prep_local_windows.ps1
Labels: Ship It

#4666 [1.12] Increase Telegraf buffer size limit to 20K
  CHANGES.md
  gen/dcos-config.yaml
Labels: Ship It

#4662 [1.13] Increase Telegraf buffer limit to 20K
  gen/dcos-config.yaml
Labels: Ship It

#4663 Fixed broken link on README.md
  README.md
Labels: Ship It

#4659 Bump dcos-diagnostics
  packages/dcos-diagnostics/buildinfo.json
Labels: merge-by-mergebot

#4683 [1.12] Bump dcos-diagnostics
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#4668 DCOS-18825 - Pin the Availability Zone per region for the AWS CF Template
  gen/aws/templates/cloudformation.json
Labels: Ship It

#4671 DCOS-46608 - docker pull image ahead of usage in test
  packages/dcos-integration-test/extra/test_applications.py
  packages/dcos-integration-test/extra/test_helpers.py
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#4667 DCOS-18825 - Pin the Availability Zone per region for the AWS CF Template
  gen/aws/templates/cloudformation.json
Labels: Ship It

#4670 DCOS-46608 - docker pull image ahead of usage in test
  packages/dcos-integration-test/extra/test_applications.py
  packages/dcos-integration-test/extra/test_helpers.py
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#4665 DCOS-18825 - Pin the Availability Zone per region for the AWS CF Template
  gen/aws/templates/cloudformation.json
Labels: Ship It

#4669 DCOS-46608 - docker pull image ahead of usage in test
  packages/dcos-integration-test/extra/test_applications.py
  packages/dcos-integration-test/extra/test_helpers.py
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#4676 [1.12] Decrease default Telegraf polling frequency
  CHANGES.md
  gen/dcos-config.yaml
Labels: Ship It

#4675 [1.13] Decrease default Telegraf polling frequency
  gen/dcos-config.yaml
Labels: Ship It

#4686 openssl: bump to 1.0.2r release
  packages/openssl/buildinfo.json
Labels: Ship It

#4705 DCOS_OSS-4875 - Backport Fix to AttributeError: 'Blob' object has no attribute id
  release/storage/azure.py
Labels: Ship It

#4704 DCOS_OSS-4875 - Backport Fix to AttributeError: 'Blob' object has no attribute 'id'
  release/storage/azure.py
Labels: Ship It

#4697 Add prefix to logged pid, and fix deprecated escape
  packages/bootstrap/extra/dcos_internal_utils/cli.py
  packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
Labels: Ship It

#4706 DCOS_OSS-4875 - Backport Fix to AttributeError: 'Blob' object has no attribute 'id'
  release/storage/azure.py
Labels: Ship It

#4712 dcos-net: ensure the desination directory exists
  CHANGES.md
  packages/dcos-net/extra/dcos-net-setup.py
Labels: merge-by-mergebot

#4713 [BACKPORT][1.11] dcos-net: ensure the desination directory exists
  CHANGES.md
  packages/dcos-net/extra/dcos-net-setup.py
Labels: Ship It

#4714 [BACKPORT][1.12] dcos-net: ensure the desination directory exists
  CHANGES.md
  packages/dcos-net/extra/dcos-net-setup.py
Labels: Ship It

#4719 DCOS_OSS-2438 - Remove use of $OPTIND in dcos-install.sh
  gen/build_deploy/bash.py
Labels: merge-by-mergebot

#4694 DCOS-49088 - Check in installer if DSS kernel modules are loaded
  CHANGES.md
  gen/build_deploy/bash.py
Labels: Ship It

#4622 [1.11] Enabled mesos launcher sealing.
  packages/mesos/build
Labels: Ship It

#4472 Turned on the mesos agent flag '--volume_gid_range'.
  gen/dcos-config.yaml
Labels: Ship It

#4720 Fixes DCOS_OSS-3739 - Fix calc error message
  gen/calc.py
Labels: Ship It

#4620 Enabled mesos launcher sealing.
  packages/mesos/build
Labels: Ship It

#4735 DCOS-49963 - Update fetch_cluster_logs.bash to include logs from the beginning of time instead of current reboot.
  fetch_cluster_logs.bash
Labels: merge-by-mergebot

#4736 [BACKPORT] [1.10] DCOS-49963 - Update fetch_cluster_logs.bash to include logs from the beginning of time instead of current reboot.
  fetch_cluster_logs.bash
Labels: Ship It

#4738 [BACKPORT] [1.12] DCOS-49963 - Update fetch_cluster_logs.bash to include logs from the beginning of time instead of current reboot.
  fetch_cluster_logs.bash
Labels: Ship It

#4729 [1.12] Bump dcos-diagnostics
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#4737 [BACKPORT] [1.11] DCOS-49963 - Update fetch_cluster_logs.bash to include logs from the beginning of time instead of current reboot.
  fetch_cluster_logs.bash
Labels: Ship It

#4744 DCOS-18825 - Update CORE OS AMI used CloudFormation templates.
  gen/aws/templates/cloudformation.json
  gen/build_deploy/aws.py
  gen/tests/test_installer_aws.py
Labels: Ship It

#4552 DCOS_OSS-4316 REX-Ray: bump to v0.11.4
  CHANGES.md
  packages/rexray/buildinfo.json
Labels: Ship It

#4730 DCOS-18825- Update CORE OS AMI used in CloudFormation templates.
  gen/aws/templates/cloudformation.json
  gen/build_deploy/aws.py
  gen/tests/test_installer_aws.py
Labels: Ship It

#4750 [master] Automated Bump DC/OS UI v2.63.1
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4723 Enable ipv6 support for l4lb
  CHANGES.md
  gen/calc.py
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#4745 DCOS-18825 - Update CORE OS AMI used CloudFormation templates.
  gen/aws/templates/cloudformation.json
  gen/build_deploy/aws.py
  gen/tests/test_installer_aws.py
Labels: Ship It

#4761 [master] Automated Bump DC/OS UI v2.64.0
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4743 DCOS-18825 - Update CORE OS AMI used CloudFormation templates.
  gen/aws/templates/cloudformation.json
  gen/build_deploy/aws.py
  gen/tests/test_installer_aws.py
Labels: Ship It

#4306 Add a test for launching pod with non-root user and ephemeral volume.
  packages/dcos-integration-test/extra/test_ucr.py
Labels: Ship It

#4789 bump of metronome 0.6.11 on dcos 1.13 master
  packages/metronome/buildinfo.json
Labels: merge-by-mergebot

#4734 [BACKPORT] [1.10] DCOS_OSS-4877 - Bump dcos-test-utils to latest.
  packages/dcos-integration-test/extra/requirements.txt
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#4795 Switched gid manager off on Mesos.
  gen/dcos-config.yaml
Labels: Ship It

#4732 [BACKPORT] [1.12] DCOS_OSS-4877 - Bump dcos-test-utils to latest.
  packages/dcos-integration-test/extra/requirements.txt
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#4733 [BACKPORT] [1.11] DCOS_OSS-4877 - Bump dcos-test-utils to latest.
  packages/dcos-integration-test/extra/requirements.txt
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#4731 DCOS_OSS-4877 - Bump dcos-test-utils to latest.
  packages/dcos-integration-test/extra/requirements.txt
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#4792 [BACKPORT] [1.11] DCOS-50823 - Mute frequently flakey tests.
  packages/dcos-integration-test/extra/requirements.txt
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#4803 gen: remove `disk:32` from min allocatable rez
  gen/dcos-config.yaml
Labels: Ship It

#4816 Mute the test for volume gid manager.
  packages/dcos-integration-test/extra/test_ucr.py
Labels: merge-by-mergebot

#4819 [master] Automated Bump DC/OS UI v2.66.8
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4786 DCOS-49926 - Updated version to 1.13.0-alpha.
  dcos_installer/test_backend.py
  gen/calc.py
Labels: Ship It

#4818 Update to version of nginx-module-vts with escape fixes
  packages/adminrouter/docker/Dockerfile
Labels: Ship It

#4782 [1.12] Fix illegal prometheus metric names
  CHANGES.md
  packages/telegraf/buildinfo.json
Labels: Ship It

#4833 [master] Automated Bump DC/OS UI v2.67.1
  packages/dcos-ui/buildinfo.json
Labels: merge-by-mergebot

#4781 Fix illegal prometheus metric names
  CHANGES.md
Labels: Ship It

#4835 [1.11] Update ip_detect_script check to 30s
  gen/calc.py
Labels: Ship It

#4701 Metronome / Marathon Removal of "Undefined" GPU Option on DCOS 1.13
  gen/calc.py
Labels: Ship It

#4825 DCOS-50823 - Mute test_checks_cli and test_vip_ipv6.
  packages/dcos-integration-test/extra/test_checks.py
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#4831 Update ip_detect_script check to 30s
  gen/calc.py
Labels: Ship It

#4834 [1.12] Update ip_detect_script check to 30s
  gen/calc.py
Labels: Ship It

#4837 DCOS-50823 - Mute flaky test_rexray.
  packages/dcos-integration-test/extra/test_rexray.py
Labels: Ship It

#4847 DCOS-50400 - Increase mesos_agent_registered_with_masters timeout
  gen/calc.py
Labels: Ship It

#4727 [1.12] Bump Mesos to nightly 1.7.x 0f8faa0
  CHANGES.md
  packages/telegraf/buildinfo.json
Labels: Ship It

#4859 [master] Automated Bump DC/OS UI v2.68.0
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4853 DCOS-47438 - Add retry to cluster identity test
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#4848 [1.12] DCOS-50400 - Increase mesos_agent_registered_with_masters timeout
  gen/calc.py
Labels: Ship It

#4874 DCOS_OSS-4922 - Mute test_rexray.test_move_external_volume_to_new_agent
  gen/calc.py
Labels: merge-by-mergebot

#4861 [1.11] Bump dcos-net
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#4813 DCOS-50170: whitelist ui update service version for unprivileged users
  packages/adminrouter/extra/src/docs/api/nginx.master.html
  packages/adminrouter/extra/src/docs/api/nginx.master.yaml
  packages/adminrouter/extra/src/includes/server/master.conf
  packages/adminrouter/extra/src/lib/auth/open.lua
Labels: Ship It

#4860 [1.12] Bump dcos-net
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#4868 Handle Prometheus output with long URL's
  packages/adminrouter/docker/Dockerfile
  packages/adminrouter/extra/src/includes/metrics-location-level.conf
  packages/adminrouter/extra/src/includes/metrics-server-level.conf
  packages/adminrouter/extra/src/test-harness/tests/test_metrics.py
Labels: Ship It

#4862 DC/OS 1.12.3-fips with OpenSSL 1.0.2r-fips.
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
  packages/openssl/build
  packages/openssl/buildinfo.json
Labels: Ship It

#4884 Check that DNS is ready before starting checks
  packages/dcos-check-runner/extra/dcos-checks-api-agent.service
  packages/dcos-check-runner/extra/dcos-checks-api-master.service
Labels: Ship It

#4896 DCOS_OSS-4952 don't remove volumes per default
  CHANGES.md
  packages/docker-gc/extra/dcos-docker-gc.service
Labels: Ship It

#4886 [1.12] Check that DNS is ready before starting checks
  packages/dcos-check-runner/extra/dcos-checks-api.service
Labels: Ship It

#4900 [1.11] DCOS-47438 - Add retry to cluster identity test
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#4897 DCOS_OSS-4952 don't remove volumes per default
  CHANGES.md
  packages/docker-gc/extra/dcos-docker-gc.service
Labels: Ship It

#4901 [1.12] DCOS-47438 - Add retry to cluster identity test
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#4908 DCOS-50400 - Unmute fixed tests
  packages/dcos-integration-test/extra/test_checks.py
Labels: Ship It

#4912 Update NAT AMIS to address CloudFormation Resource Errors
  gen/aws/templates/advanced/advanced-master.json
  gen/aws/templates/advanced/advanced-priv-agent.json
  gen/aws/templates/advanced/advanced-pub-agent.json
  gen/aws/templates/advanced/zen.json
  gen/build_deploy/aws.py
Labels: Ship It

#4911 Update NAT AMIS to address CloudFormation Resource Errors
  gen/aws/templates/advanced/advanced-master.json
  gen/aws/templates/advanced/advanced-priv-agent.json
  gen/aws/templates/advanced/advanced-pub-agent.json
  gen/aws/templates/advanced/infra.json
  gen/aws/templates/advanced/zen.json
  gen/aws/templates/cloudformation.json
  gen/build_deploy/aws.py
Labels: Ship It

#4909 CHANGES.md: Improve X-Frame-Options note
  CHANGES.md
Labels: Ship It

#4915 Add HTTP status collection to server level
  packages/adminrouter/extra/src/includes/metrics-server-level.conf
Labels: Ship It

#4906 Bump dcos-ui-update-service package
  packages/dcos-ui-update-service/buildinfo.json
Labels: Ship It

#4926 Remove double annotations
  packages/adminrouter/extra/src/includes/server/open/agent.conf
  packages/adminrouter/extra/src/includes/server/open/master.conf
Labels: Ship It

#4933 Bump marathon to 1.5.14
  packages/marathon/buildinfo.json
Labels: Ship It

#4924 gen/dcos-config.yaml: Remove nginx_vts_upstream and nginx_vts_server metrics
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_metrics.py
Labels: Ship It
