Repository dcos/dcos, pull requests merged in 2019-11, with the labels that each got.

#6473 docker-gc: don't run `system prune`
  packages/docker-gc/extra/dcos-docker-gc.service
Labels: Ship It

#6498 [1.12] Bump dcos-net
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#6497 [1.13] Bump dcos-net
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#6496 [2.0] Bump dcos-net
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#6490 chore: Bump DC/OS UI v2.83.0
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ready For Review

#6492 Bump Mesos modules
  CHANGES.md
  packages/mesos-modules/buildinfo.json
Labels: merge-by-mergebot

#6495 [1.12] Bump Mesos modules
  CHANGES.md
Labels: Ship It

#6494 [1.13] Bump Mesos modules
  CHANGES.md
  packages/mesos-modules/buildinfo.json
Labels: Ship It

#6480 Bump dcos-net
  CHANGES.md
  gen/calc.py
  gen/dcos-config.yaml
  packages/dcos-net/buildinfo.json
Labels: Ship It

#6521 Feature/winpanda
  pkgpanda/docker.windows/dcos-builder/Dockerfile
  pkgpanda/docker.windows/dcos-builder/setup-python36.ps1
Labels: merge-by-mergebot

#6493 [2.0] Bump Mesos modules
  CHANGES.md
  packages/mesos-modules/buildinfo.json
Labels: Ship It

#6527 1.11.14-dev
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
Labels: merge-by-mergebot

#6528 Update fix version map with 1.11.14
  mergebot-config.json
Labels: merge-by-mergebot

#6519 DCOS_OSS-5648: added prerequisites.zip; updated dcos_install.ps1
  build_genconf_windows.ps1
  build_local_windows.ps1
  gen/build_deploy/powershell/dcos_install.ps1
  gen/build_deploy/powershell/install_choco.ps1
Labels: Ship It

#6526 Winpanda App: Add Support For Extra DC/OS Package Installation Helpers
  packages/winpanda/extra/src/winpanda/core/utils.py
  packages/winpanda/extra/src/winpanda/requirements.txt
Labels: Ship It

#6525 Update libpq to 9.6.15
  CHANGES.md
  packages/libpq/buildinfo.json
Labels: Ship It

#6556 DCOS_OSS-5672: 3 fixes to dcos_install.ps1
  gen/build_deploy/powershell/dcos_install.ps1
Labels: Ship It

#6553 Updated tar_mode for windows variant
  gen/build_deploy/powershell/dcos_install.ps1
Labels: Ship It

#6558 Winpanda App: Fix Recognition Of Configuration File Templates
  packages/winpanda/extra/src/winpanda/common/storage.py
  packages/winpanda/extra/src/winpanda/common/utils.py
  packages/winpanda/extra/src/winpanda/core/package/manifest.py
  packages/winpanda/extra/src/winpanda/extm/extm.py
Labels: Ship It

#6567 Add Tim Harper to owners.json
  owners.json
Labels: merge-by-mergebot

#6542 2.1 - bump Marathon to 1.9.109
  packages/marathon/buildinfo.json
Labels: Ship It

#6482 Unified Mesos with its respective modules - specific to the variant.
  gen/dcos-config.yaml
  packages/mesos-modules/build
  packages/mesos-modules/buildinfo.json
  packages/mesos/build
  packages/mesos/buildinfo.json
Labels: Ship It

#6566 Use new CLI to generate diagnostics bundle
  fetch_cluster_logs.bash
Labels: Ship It

#6578 Remove people from owners file
  owners.json
Labels: Ship It

#6584 Update owners.json
  owners.json
Labels: Ship It
