Repository dcos/dcos, pull requests merged in 2019-02, with the labels that each got.

#4404 [1.12] DCOS-16098 - Correct filename in dcos_generate_config.ee.sh help
  gen/build_deploy/bash/installer_internal_wrapper.in
Labels: Ship It

#4410 Fix the mergebot config for 1.11
  mergebot-config.json
Labels: Ready For Review

#4405 [1.11] DCOS-16098 - Correct filename in dcos_generate_config.ee.sh help
  gen/build_deploy/bash/installer_internal_wrapper.in
Labels: Ship It

#4394 Add detect_ip to diagnostics bundle
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#4397 DCOS-16098 - Correct filename in dcos_generate_config.ee.sh help
  gen/build_deploy/bash/installer_internal_wrapper.in
Labels: Ship It

#4373 [1.11] Automated Bump DC/OS UI v1.26.7
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4421 [1.12] Exclude prometheus_client from windows build
  packages/windows.treeinfo.json
Labels: Ship It

#4388 Use Python's tarfile in make_tar to avoid Linux/macOS difference in tar distributions
  packages/dcos-image-deps/buildinfo.json
  packages/liblzma/build
  packages/liblzma/buildinfo.json
  packages/python/buildinfo.json
  pkgpanda/__init__.py
  pkgpanda/docker/dcos-builder/Dockerfile
  pkgpanda/test_util.py
  pkgpanda/util.py
Labels: Ship It

#4409 [DCOS-45428] Bump cosmos to latest version
  packages/cosmos/buildinfo.json
Labels: Ship It

#4422 [1.12][DCOS-45428] Bump cosmos to latest version
  packages/cosmos/buildinfo.json
Labels: Ship It

#4437 (1.11) Unmute test_metrics_containers
  packages/dcos-integration-test/extra/test_metrics.py
Labels: Ship It

#4440 [master] Automated Bump DC/OS UI v2.52.0
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4165 [1.12] Fix hello-world flaky teardown
  packages/dcos-integration-test/extra/test_metrics.py
Labels: Ship It

#4151 [1.13] Fix hello-world flaky teardown
  packages/dcos-integration-test/extra/test_metrics.py
Labels: Ship It

#4445 Exercise test-e2e on dcos/dcos
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4459 [master] Automated Bump DC/OS UI v2.52.2
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4454 DCOS-48052: 1.12.2
  packages/mesos/build
  packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
  packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
  packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
  packages/mesos/extra/patches/0004-Added-received-timestamp-into-process-Request.patch
  packages/mesos/extra/patches/0005-Added-task-health-check-definitions-to-master-API-re.patch
  packages/mesos/extra/patches/0006-Introduced-logResponse-for-http-handlers.patch
  packages/mesos/extra/patches/0007-Logged-request-processing-time-for-some-endpoints.patch
  packages/mesos/extra/patches/0008-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
  packages/mesos/extra/patches/0009-Added-HEARTBEAT-events-and-calls-for-the-executor-HT.patch
  packages/mesos/extra/patches/0010-Refactored-master-and-agent-streaming-connections.patch
  packages/mesos/extra/patches/0011-Added-heartbeaters-for-agent-and-HTTP-executors.patch
  packages/mesos/extra/patches/0012-Added-tests-for-agent-executor-heartbeating.patch
  packages/mesos/extra/patches/0013-Changed-master-to-hold-subscribers-in-a-circular-buf.patch
  packages/mesos/extra/patches/0014-Added-gauge-metric-for-operator-event-stream-subscri.patch
  packages/mesos/extra/patches/0015-Reverted-the-container-sandbox-permission-from-0750-.patch
  packages/mesos/extra/patches/0016-Added-Linux-memfd-support.patch
  packages/mesos/extra/patches/0017-Made-the-code-more-robust-related-to-sendfile.patch
  packages/mesos/extra/patches/0018-Added-a-test-to-test-memfd-file-clone.patch
  packages/mesos/extra/patches/0019-Updated-handleWhitelistFds-to-avoid-closing-FDs-with.patch
  packages/mesos/extra/patches/0020-Cloned-a-sealed-file-of-launcher-binary.patch
  packages/mesos/extra/patches/0021-Cleaned-up-command-executor-redundant-command-string.patch
  packages/mesos/extra/patches/0022-Added-enable-launcher-sealing-compiler-flag.patch
  packages/mesos/extra/patches/0023-Enabled-launcher-sealing-depending-on-corresponding-.patch
  packages/mesos/extra/patches/0024-Fixed-ROOT_PidNamespace-test-after-enabling-launcher.patch
  packages/mesos/extra/patches/0025-Secured-mesos-executor-binary-using-memfd.patch
Labels: Ship It

#4473 Revert back to platform-dependent tar decompression
  pkgpanda/util.py
Labels: Ship It

#4449 DCOS-46438 - Support collecting integration tests locally without a cluster.
  packages/dcos-integration-test/extra/requirements.txt
  tox.ini
Labels: Ship It

#4471 DCOS-48052: 1.10.10.1
  packages/mesos/build
  packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
  packages/mesos/extra/patches/0002-Mesos-UI-Change-paths-pailer-and-logs-to-work-with-a.patch
  packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch
  packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
  packages/mesos/extra/patches/0005-Included-nested-command-check-output-in-the-executor.patch
  packages/mesos/extra/patches/0006-Made-the-log-output-handling-of-TCP-and-HTTP-checks-.patch
  packages/mesos/extra/patches/0007-Raised-the-logging-level-of-some-check-and-health-ch.patch
  packages/mesos/extra/patches/0008-Improved-logging-for-offers-and-inverse-offers.patch
  packages/mesos/extra/patches/0009-Logged-the-resources-in-DRF-sorter-CHECKs.patch
  packages/mesos/extra/patches/0010-Added-verbose-logging-in-Sorter-Allocation.patch
  packages/mesos/extra/patches/0011-Put-TerminateEvent-at-the-end-of-the-queue-in-the-Me.patch
  packages/mesos/extra/patches/0012-Waited-for-TEARDOWN-to-be-sent-in-v1-Java-scheduler-.patch
  packages/mesos/extra/patches/0013-Added-task-health-check-definitions-to-master-API-re.patch
  packages/mesos/extra/patches/0014-Added-Linux-memfd-support.patch
  packages/mesos/extra/patches/0015-Made-the-code-more-robust-related-to-sendfile.patch
  packages/mesos/extra/patches/0016-Added-a-test-to-test-memfd-file-clone.patch
  packages/mesos/extra/patches/0017-Cloned-a-sealed-file-of-launcher-binary.patch
  packages/mesos/extra/patches/0018-Cleaned-up-command-executor-redundant-command-string.patch
  packages/mesos/extra/patches/0019-Added-disable-libtool-wrapper-configuration-to-Mesos.patch
  packages/mesos/extra/patches/0020-Added-enable-launcher-sealing-compiler-flag.patch
  packages/mesos/extra/patches/0021-Enabled-launcher-sealing-depending-on-corresponding-.patch
  packages/mesos/extra/patches/0022-Fixed-ROOT_PidNamespace-test-after-enabling-launcher.patch
  packages/mesos/extra/patches/0023-Secured-mesos-executor-binary-using-memfd.patch
Labels: Ready For Review

#4470 DCOS-48052: 1.11.9.1
  packages/mesos/build
  packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
  packages/mesos/extra/patches/0002-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
  packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch
  packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
  packages/mesos/extra/patches/0005-Displayed-resource-provider-resources-in-GET_RESOURC.patch
  packages/mesos/extra/patches/0006-Improved-logging-for-offers-and-inverse-offers.patch
  packages/mesos/extra/patches/0007-Introduced-a-push-based-gauge-metric.patch
  packages/mesos/extra/patches/0008-Added-a-test-for-PushGauge.patch
  packages/mesos/extra/patches/0009-Renamed-Gauge-to-PullGauge-and-documented-difference.patch
  packages/mesos/extra/patches/0010-Updated-mesos-source-for-Gauge-PullGauge-renaming.patch
  packages/mesos/extra/patches/0011-Enabled-per-framework-metrics-in-the-master.patch
  packages/mesos/extra/patches/0012-Added-per-framework-subscribed-metric-and-helpers.patch
  packages/mesos/extra/patches/0013-Added-per-framework-metrics-for-scheduler-calls.patch
  packages/mesos/extra/patches/0014-Added-per-framework-metrics-for-scheduler-events.patch
  packages/mesos/extra/patches/0015-Added-per-framework-offer-metrics.patch
  packages/mesos/extra/patches/0016-Added-per-framework-metrics-for-task-states.patch
  packages/mesos/extra/patches/0017-Added-per-framework-metrics-for-offer-operations.patch
  packages/mesos/extra/patches/0018-Enabled-per-framework-metrics-in-the-allocator.patch
  packages/mesos/extra/patches/0019-Changed-the-capacity_-member-of-BoundedHashMap-to-no.patch
  packages/mesos/extra/patches/0020-Tracked-completed-framework-metrics-in-the-allocator.patch
  packages/mesos/extra/patches/0021-Added-per-framework-metrics-for-suppressed-roles.patch
  packages/mesos/extra/patches/0022-Added-task-health-check-definitions-to-master-API-re.patch
  packages/mesos/extra/patches/0023-Put-TerminateEvent-at-the-end-of-the-queue-in-the-Me.patch
  packages/mesos/extra/patches/0024-Waited-for-TEARDOWN-to-be-sent-in-v1-Java-scheduler-.patch
  packages/mesos/extra/patches/0025-Added-Linux-memfd-support.patch
  packages/mesos/extra/patches/0026-Made-the-code-more-robust-related-to-sendfile.patch
  packages/mesos/extra/patches/0027-Added-a-test-to-test-memfd-file-clone.patch
  packages/mesos/extra/patches/0028-Cloned-a-sealed-file-of-launcher-binary.patch
  packages/mesos/extra/patches/0029-Cleaned-up-command-executor-redundant-command-string.patch
  packages/mesos/extra/patches/0030-Added-enable-launcher-sealing-compiler-flag.patch
  packages/mesos/extra/patches/0031-Enabled-launcher-sealing-depending-on-corresponding-.patch
  packages/mesos/extra/patches/0032-Fixed-ROOT_PidNamespace-test-after-enabling-launcher.patch
  packages/mesos/extra/patches/0033-Secured-mesos-executor-binary-using-memfd.patch
Labels: Ready For Review

#4480 update version to 1.10.10.1
  dcos_installer/test_backend.py
  gen/calc.py
Labels: Ready For Review

#4478 Update DC/OS Version number to 1.11.9.1
  dcos_installer/test_backend.py
  gen/calc.py
Labels: Ready For Review

#4431 Integration test for user account functionality
  packages/dcos-integration-test/extra/test_iam.py
Labels: Ship It

#4493 Update DC/OS version to 1.10.11
  dcos_installer/test_backend.py
  gen/calc.py
Labels: Ready For Review

#4494 update the version of DC/OS to 1.11.10
  dcos_installer/test_backend.py
  gen/calc.py
Labels: Ready For Review

#4362 Open /package/describe and /package/resource to any authenticated user
  packages/adminrouter/extra/src/docs/api/nginx.master.html
  packages/adminrouter/extra/src/docs/api/nginx.master.yaml
  packages/adminrouter/extra/src/includes/server/master.conf
  packages/adminrouter/extra/src/lib/auth/open.lua
Labels: Ship It

#4446 Revert "packages/cockroach: improve iam-database-restore script"
  packages/cockroach/extra/iam-database-restore
Labels: Ship It

#4477 DCOS-46438 - Do not use vulnerable PyYaml version in tests.
  packages/dcos-integration-test/extra/requirements.txt
Labels: Ship It

#4479 DCOS-47966 Enable UI-Update plugin for UI
  gen/calc.py
  gen/dcos-config.yaml
Labels: Ship It

#4497 Update Mergebot Fix Versions.
  mergebot-config.json
Labels: Ready For Review

#4481 DCOS-46438 - Synchronize integration test requirements with panda package versions.
  packages/dcos-integration-test/extra/requirements.txt
  packages/dcos-test-utils/buildinfo.json
  tox.ini
Labels: Ship It

#4474 [BACKPORT] [1.11] DCOS-46438 - Support collecting integration tests locally without a cluster.
  packages/dcos-integration-test/extra/requirements.txt
  tox.ini
Labels: Ship It

#4485 Metronome PID is not written to this location
  packages/metronome/build
Labels: Ship It

#4475 [BACKPORT] [1.12] DCOS-46438 - Support collecting integration tests locally without a cluster.
  packages/dcos-integration-test/extra/requirements.txt
  tox.ini
Labels: Ship It

#4503 [1.11] Include docker ps in diagnostics bundle
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#4443 Remove flaky test marker for DCOS-41819
  packages/dcos-integration-test/extra/test_units.py
Labels: Ship It

#4499 Include docker ps in diagnostics bundle
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#4500 [DCOS-45174] Unmute test_units.test_socket_files
  packages/dcos-integration-test/extra/test_units.py
Labels: Ship It

#4484 [1.11] DCOS_OSS-4097 - Explicitly create user groups in pkgpanda
  pkgpanda/__init__.py
Labels: Ship It

#4483 [1.12] DCOS_OSS-4097 - Explicitly create user groups in pkgpanda
  pkgpanda/__init__.py
Labels: Ship It

#4501 [1.12] include docker ps in diagnostic bundle
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#4504 [1.12] Unmute test_units.test_socket_files
  packages/dcos-integration-test/extra/test_units.py
Labels: Ship It

#4523 [1.12] Bump dcos-diagnostics
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#4482 DCOS_OSS-4097 - Explicitly create user groups in pkgpanda
  pkgpanda/__init__.py
Labels: Ship It

#4517 Grow Telegraf's statsd UDP message queue
  gen/dcos-config.yaml
Labels: Ship It

#4541 Revert "Merge #4484" -DCOS_OSS-4097 - Explicitly create user groups in pkgpanda
  pkgpanda/__init__.py
Labels: merge-by-mergebot

#4522 Bunp dcos-diagnostics
  packages/dcos-diagnostics/buildinfo.json
Labels: Ship It

#4539 [master] Automated Bump DC/OS UI v2.54.1
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4304 Add basic support for prometheus
  CHANGES.md
  gen/dcos-config.yaml
  packages/dcos-net/buildinfo.json
Labels: Ship It

#4554 [master] Automated Bump DC/OS UI v2.55.0
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4545 Add test to check if bundle contains frameworks
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#4551 Re-enable test_checks_cli test
  packages/dcos-integration-test/extra/test_checks.py
Labels: Ship It

#4512 Instruct Mesos master to include port resources in offers.
  gen/dcos-config.yaml
Labels: Ship It

#4513 Instruct Mesos master to include port resources in offers.
  gen/dcos-config.yaml
Labels: Ship It

#4563 Backport removal of flaky test marker to 1.12
  packages/dcos-integration-test/extra/test_units.py
Labels: Ship It

#4577 [1.11] Add test to check if bundle contains frameworks
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#4576 [1.12] Add test to check if bundle contains frameworks
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#4571 Introduce test-e2e to dcos/dcos 1.10
  test-e2e/README.md
  test-e2e/cluster_helpers.py
  test-e2e/conftest.py
  test-e2e/requirements.txt
  test-e2e/test_e2e_module.py
  test-e2e/test_groups.yaml
  test-e2e/test_make_disk_resources.py
  tox.ini
Labels: Ship It

#4597 Fix tests for schema 0.7.0
  gen/tests/test_config.py
Labels: merge-by-mergebot

#4598 (1.12) Fix tests for schema 0.7.0
  gen/tests/test_config.py
Labels: merge-by-mergebot

#4600 (1.11) Fix tests for schema 0.7.0
  gen/tests/test_config.py
Labels: merge-by-mergebot

#4601 (1.10) Fix tests for schema 0.7.0
  gen/tests/test_config.py
Labels: merge-by-mergebot

#4604 Updated contacts and team email for tests from marathon-team to orchestration-team
  packages/dcos-integration-test/extra/test_applications.py
  packages/dcos-integration-test/extra/test_metronome.py
  packages/dcos-integration-test/extra/test_packaging.py
Labels: merge-by-mergebot

#4572 Introduce test-e2e to dcos/dcos 1.11
  test-e2e/README.md
  test-e2e/cluster_helpers.py
  test-e2e/conftest.py
  test-e2e/requirements.txt
  test-e2e/test_e2e_module.py
  test-e2e/test_groups.yaml
  test-e2e/test_make_disk_resources.py
  tox.ini
Labels: Ship It

#4549 DCOS-46615 - Retry downloading pkgpanda pkg if file size incorrect
  pkgpanda/exceptions.py
  pkgpanda/test_util.py
  pkgpanda/util.py
Labels: merge-by-mergebot

#4588 [1.11] DCOS-46615 - Retry downloading pkgpanda pkg if file size incorrect
  pkgpanda/exceptions.py
  pkgpanda/test_util.py
  pkgpanda/util.py
Labels: Ship It

#4590 Bump marathon for 1.12
  packages/marathon/buildinfo.json
Labels: Ship It

#4506 Introduce test-e2e to dcos/dcos 1.12
  test-e2e/README.md
  test-e2e/cluster_helpers.py
  test-e2e/conftest.py
  test-e2e/requirements.txt
  test-e2e/test_e2e_module.py
  test-e2e/test_groups.yaml
  test-e2e/test_make_disk_resources.py
  tox.ini
Labels: Ship It

#4578 Unmute test_metronome
  packages/dcos-integration-test/extra/test_metronome.py
Labels: Ship It

#4579 Unmute test_checks
  packages/dcos-integration-test/extra/test_checks.py
Labels: Ship It

#4587 [1.12] DCOS-46615 - Retry downloading pkgpanda pkg if file size incorrect
  pkgpanda/exceptions.py
  pkgpanda/test_util.py
  pkgpanda/util.py
Labels: Ship It

#4605 [1.12] Automated Bump DC/OS UI v2.26.10
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4610 [1.12] Automated Bump DC/OS UI v2.26.11
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#4615 Fix dcos-image cryptography package dep.
  packages/dcos-image-deps/build
  packages/dcos-image-deps/buildinfo.json
  setup.py
  test-e2e/requirements.txt
Labels: merge-by-mergebot

#4626 Require wheel package as a dependency for dcos-image.
  packages/dcos-image-deps/build
  packages/dcos-image-deps/buildinfo.json
  setup.py
  test-e2e/requirements.txt
Labels: merge-by-mergebot

#4625 Require wheel package as a dependency for dcos-image.
  packages/dcos-image-deps/build
  packages/dcos-image-deps/buildinfo.json
  setup.py
  test-e2e/requirements.txt
Labels: merge-by-mergebot

#4624 Cherry Pick fix for DCOS-49198 - Fix dcos-image dependency.
  packages/dcos-image-deps/build
  packages/dcos-image-deps/buildinfo.json
  setup.py
  test-e2e/requirements.txt
Labels: merge-by-mergebot

#4211 Bump dcos-test-utils
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#4631 [master] Automated Bump DC/OS UI v2.57.0
  packages/dcos-ui/buildinfo.json
Labels: merge-by-mergebot

#4630 DCOS-48402 - Add new EnvironmentFiles to Mesos systemd units
  packages/mesos/extra/dcos-mesos-master.service
  packages/mesos/extra/dcos-mesos-slave-public.service
  packages/mesos/extra/dcos-mesos-slave.service
Labels: Ship It

#4629 DCOS-46615 - Make pkgpanda resistant to missing content-length
  pkgpanda/test_util.py
  pkgpanda/util.py
Labels: Ship It

#4632 [DCOS_OSS-4844] Fix master node replacement test
  test-e2e/test_master_node_replacement.py
Labels: Ship It

#4621 [1.12] Enabled mesos launcher sealing.
  packages/mesos/build
Labels: Ship It
