Repository dcos/dcos, pull requests merged in 2019-12, with the labels that each got.

#6589 DCOS_OSS-5689: [Windows BETA] Winpanda.py vs Dcos_Install.PS1 integration fix.
  gen/build_deploy/powershell/dcos_install.ps1
Labels: Ship It

#6588 Fix type of paths read from JSON file
  packages/bootstrap/extra/dcos_internal_utils/utils.py
Labels: Ship It

#6590 Dcos4windows
  packages/winpanda/extra/src/winpanda/cfgm/__init__.py
  packages/winpanda/extra/src/winpanda/cfgm/cfgm.py
  packages/winpanda/extra/src/winpanda/cfgm/exceptions.py
  packages/winpanda/extra/src/winpanda/common/storage.py
  packages/winpanda/extra/src/winpanda/core/command.py
  packages/winpanda/extra/src/winpanda/core/constants.py
  packages/winpanda/extra/src/winpanda/core/package/manifest.py
  packages/winpanda/extra/src/winpanda/core/package/package.py
  packages/winpanda/extra/src/winpanda/docs/PLACEHOLDER.md
Labels: Ship It

#6592 Add Windows path variables to gen
  gen/calc.py
  gen/dcos-config-windows.yaml
  gen/tests/test_config.py
Labels: Ship It

#6595 Remove timaa2k and mhrabovcin as an owner
  owners.json
Labels: Ship It

#6593 Added placeholder for running bootstrap.py on windows by winpanda
  packages/bootstrap/extra/bootstrap.extra.j2
  packages/bootstrap/extra/bootstrap.ps1
  packages/bootstrap/windows.build.ps1
  packages/bootstrap/windows.buildinfo.json
Labels: Ship It

#6606 Do not template files without .j2 suffix
  packages/winpanda/extra/src/winpanda/cfgm/cfgm.py
Labels: Work In Progress

#6602 Winpanda App: Add Fetching dcos-config-windows.yaml From Linux Part O…
  packages/winpanda/extra/src/winpanda/cfgm/cfgm.py
  packages/winpanda/extra/src/winpanda/core/cmdconf.py
  packages/winpanda/extra/src/winpanda/core/command.py
  packages/winpanda/extra/src/winpanda/core/package/manifest.py
  packages/winpanda/extra/src/winpanda/core/package/package.py
  packages/winpanda/extra/src/winpanda/core/rc_ctx.py
  packages/winpanda/extra/src/winpanda/docs/PLACEHOLDERS.md
Labels: Ready For Review

#6579 Remove dcos-config-windows package from Windows build
  gen/__init__.py
Labels: Work In Progress

#6615 [1.12] set interfaces as unmanaged by coreos networkd
  CHANGES.md
  packages/dcos-net/extra/dcos-net-setup.py
Labels: Ship It

#6603 [1.13] packages/cockroach: use golang 1.10.8 for build
  CHANGES.md
  packages/cockroach/build
Labels: Ship It

#6613 [2.0] set interfaces as unmanaged by coreos networkd
  CHANGES.md
  packages/dcos-net/extra/dcos-net-setup.py
Labels: Ship It

#6548 [master] set interfaces as unmanaged by coreos networkd
  CHANGES.md
  packages/dcos-net/extra/dcos-net-setup.py
Labels: Ship It

#6614 [1.13] set interfaces as unmanaged by coreos networkd
  CHANGES.md
  packages/dcos-net/extra/dcos-net-setup.py
Labels: Ship It

#6627 Winpanda App: Adjust Log Directory Location
  packages/winpanda/extra/src/winpanda/bin/winpanda.py
  packages/winpanda/extra/src/winpanda/common/constants.py
Labels: merge-by-mergebot

#6622 Backport MESOS-9968 to DC/OS 1.13
  CHANGES.md
  packages/mesos/buildinfo.json
Labels: merge-by-mergebot

#6621 Backport MESOS-9968 to DC/OS 2.0
  CHANGES.md
  packages/mesos/buildinfo.json
Labels: merge-by-mergebot

#6628 Winpanda App: Tolerate Service Start Failures
  packages/winpanda/extra/src/winpanda/common/utils.py
  packages/winpanda/extra/src/winpanda/core/command.py
  packages/winpanda/extra/src/winpanda/svcm/exceptions.py
  packages/winpanda/extra/src/winpanda/svcm/nssm.py
Labels: Ready For Review

#6630 Deleted not used paths and fix agent-port and Location for mesos-agent logs in dcos-config-windows.yaml
  packages/dcos-diagnostics/extra/dcos-diagnostics.nssm.j2
Labels: Ship It

#6647 Update Mergebot Fix Versions.
  mergebot-config.json
Labels: merge-by-mergebot

#6645 Winpanda App: Fix Package Shared Config Dir Auto-Cleanup On Package S…
  packages/winpanda/extra/src/winpanda/cfgm/cfgm.py
  packages/winpanda/extra/src/winpanda/core/command.py
Labels: Ship It

#6642 [BUGFIX] [Windows BETA] DCOS_OSS-5744: dcos_install.ps1
  gen/build_deploy/powershell/dcos_install.ps1
Labels: Ship It

#6637 Add output of `df` to diagnostics bundle
  gen/dcos-config.yaml
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: Ship It

#6653 updated bootstrap package to be built for windows variant
  packages/bootstrap/windows.buildinfo.json
  packages/windows.treeinfo.json
Labels: Ship It

#6656 Winpanda App: Add Bootstrap Package Into Sorted Dependency List
  packages/winpanda/extra/src/winpanda/core/utils.py
Labels: Ship It

#6671 DCOS_OSS-5783: Combine dcos_install URL and version into single URL
  gen/build_deploy/powershell/dcos_install.ps1
Labels: Ship It

#6679 Winpanda App: Fix Sparse Package Configuration Processing
  packages/winpanda/extra/src/winpanda/core/command.py
Labels: Ship It

#6684 Modify Mesos agent start up in Windows to support fault domain (DCOS_OSS-5796)
  gen/dcos-config-windows.yaml
  packages/mesos/extra/mesos.nssm.j2
Labels: Ship It

#6562 [2.0] Compile Admin Router without SSE4.2 instructions
  CHANGES.md
  packages/adminrouter/docker/build-resty.sh
Labels: Ship It

#6689 Update fix version to 1.13.8
  mergebot-config.json
Labels: merge-by-mergebot

#6688 1.13.8 dev
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
Labels: merge-by-mergebot

#6678 Compile Admin Router without SSE4.2 instructions
  packages/adminrouter/docker/build-resty.sh
Labels: Ship It

#6692 Added linting for DC/OS commits.
  .gitlint
  .pre-commit-config.yaml
  README.md
Labels: merge-by-mergebot

#6695 Only one approval required on PRs
  mergebot-config.json
Labels: merge-by-mergebot

#6704 fix launch parametrs mesos-agent (OSS) (DCOS_OSS-5805)
  packages/mesos/extra/mesos.nssm.j2
Labels: merge-by-mergebot

#6697 [master] Fix test_metrics
  packages/dcos-integration-test/extra/test_metrics.py
Labels: merge-by-mergebot

#6700 Unicom 1.12.5
  gen/build_deploy/bash.py
Labels: Ship It

#6703 Require Windows tox tests to pass
  mergebot-config.json
Labels: Ship It

#6702 Document how to test winpanda
  packages/winpanda/extra/pytest.ini
  packages/winpanda/extra/src/winpanda/README.md
  tox.ini
Labels: Ship It

#6691 admin router: prevent adminrouter from passing authrization header to etcd
  packages/adminrouter/extra/src/nginx.master.conf
Labels: Ship It

#6708 Update log location (DCOS_OSS-5806)
  gen/dcos-config-windows.yaml
Labels: Ship It

#6710 [2.0] Fix metrics test
  packages/dcos-integration-test/extra/test_metrics.py
Labels: Ship It

#6711 [1.13] Fix test_metrics
  packages/dcos-integration-test/extra/test_metrics.py
Labels: Ship It

#6716 add doc for calico networking in DC/OS
  packages/calico/README.md
Labels: Ship It

#6715 Add Windows run process tests
  packages/winpanda/extra/src/winpanda/common/utils.py
  packages/winpanda/extra/src/winpanda/tests/test_common_utils.py
Labels: Ship It
