Repository dcos/dcos, pull requests merged in 2020-04, with the labels that each got.

#7119 Remove ip-detect and fault-domain download from Windows upgrade
  gen/build_deploy/powershell/dcos_node_upgrade.ps1.in
Labels: merge-by-mergebot

#7075 Marathon 1.10 bump (Resource Limits Support)
  CHANGES.md
  packages/dcos-integration-test/extra/test_networking.py
  packages/marathon/buildinfo.json
  packages/marathon/extra/marathon.sh
Labels: Ship It

#7122 Make Tomasz and Karsten owners.
  owners.json
Labels: Ship It

#7131 Update version to 2.1.0-rc1-dev
  dcos_installer/test_backend.py
  gen/calc.py
  packages/winpanda/extra/src/winpanda/tests/data/expanded.config.full.json
Labels: merge-by-mergebot

#7126 Copy Telegraf extra file into Windows package
  packages/telegraf/windows.build.ps1
Labels: Ship It

#7123 Log dcos config rendering at info level
  packages/winpanda/extra/src/winpanda/core/command.py
  packages/winpanda/extra/src/winpanda/tests/integration/test_dcos_config.py
Labels: Ship It

#7125 Cleanup spelling and incorrect backslashes
  gen/build_deploy/powershell/dcos_generate_config_win.sh.in
  packages/adminrouter/extra/src/lib/auth/common.lua
  packages/adminrouter/extra/src/lib/util.lua
  packages/mesos/extra/mesos.nssm.j2
  packages/winpanda/extra/src/winpanda/core/command.py
Labels: Ship It

#7088 Bump dcos-test-utils
  packages/dcos-integration-test/requirements.txt
  packages/dcos-test-utils/buildinfo.json
Labels: Ship It

#7137 Use local repo for OpenResty
  CHANGES.md
  packages/adminrouter/windows.buildinfo.json
Labels: Ship It

#7141 Only install modules if needed
  build_local_windows.ps1
Labels: merge-by-mergebot

#7011 Create commit based SHA for windows artifacts
  build_local_windows.ps1
Labels: Ship It

#7143 [2.0] Update OpenResty to 1.15.8.3
  CHANGES.md
  packages/adminrouter/docker/Dockerfile
Labels: Ship It

#7127 D2IQ-66446 Upgrade fails on dcos-diagnostics service stop
  packages/winpanda/extra/src/winpanda/svcm/nssm.py
  packages/winpanda/extra/src/winpanda/tests/unit/test_svcm_nssm.py
Labels: Ship It

#7142 Fix missing concatentation operator
  packages/adminrouter/extra/src/lib/cache.lua
Labels: Ship It

#7129 Note an important breaking change
  CHANGES.md
Labels: Ship It

#7133 Enable Telegraf test on Windows.
  packages/dcos-integration-test/extra/test_metrics.py
Labels: Ship It

#7146 Call bootstrap.ps1 when installing Mesos on Windows
  packages/mesos/extra/mesos.ps1
Labels: Ship It

#7148 Update CoreOS AMIs for cloudformation
  gen/build_deploy/aws.py
Labels: Ship It

#7152 Update OpenSSL on Linux to 1.1.1f
  CHANGES.md
  packages/openssl/buildinfo.json
Labels: Ship It

#7155 D2IQ-66497: avoid clean up of C:\d2iq\dcos\var dir
  packages/winpanda/extra/src/winpanda/core/command.py
Labels: Ship It

#7153 Reduce Windows machine size
  test_util/main.tf
Labels: Ready For Review

#7158 Move Linux openssl to Mesosphere repo
  packages/openssl/buildinfo.json
Labels: merge-by-mergebot

#7157 Drop Statsd tests for Windows.
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
  packages/dcos-integration-test/extra/test_metrics.py
Labels: Ship It

#7159 Updated OpenSSL on Windows to 1.1.1f.
  packages/mesos-modules/windows.build.ps1
  packages/mesos-modules/windows.buildinfo.json
  packages/mesos/windows.build.ps1
  packages/mesos/windows.buildinfo.json
  packages/openssl/windows.build.ps1
  packages/openssl/windows.buildinfo.json
Labels: Ship It

#7163 [2.0] Update OpenSSL to 1.1.1f
  CHANGES.md
  packages/openssl/buildinfo.json
Labels: Ship It

#7164 [1.13] Update to OpenSSL 1.0.2u
  CHANGES.md
  packages/openssl/buildinfo.json
Labels: Ship It

#7160 D2IQ-66671 Downgrade back to master failed
  packages/winpanda/extra/src/winpanda/core/command.py
  packages/winpanda/extra/src/winpanda/core/package/package.py
Labels: Ship It

#7115 Do not require diagnostics on destroy.
  test_util/Makefile
Labels: Ship It

#7165 [1.12] Update to OpenSSL 1.0.2u
  CHANGES.md
  packages/openssl/buildinfo.json
Labels: Ship It

#7167 [master] Bump Mesos to nightly master e6b15b1
  CHANGES.md
  packages/mesos-modules/windows.buildinfo.json
  packages/mesos/buildinfo.json
  packages/mesos/windows.buildinfo.json
Labels: Ship It

#7171 Set TLS to 1.2 in Windows build script
  build_local_windows.ps1
Labels: Ship It

#6471 chore: bump update service
  packages/dcos-ui-update-service/buildinfo.json
Labels: Ship It

#7178 Updated cmake in dcos-builder docker image.
  pkgpanda/docker/dcos-builder/Dockerfile
Labels: Ship It

#7176 Fix an integration test for nested cgroups support.
  packages/dcos-integration-test/extra/test_ucr.py
Labels: Ship It

#7181 Update owners.json
  owners.json
Labels: Ship It

#7179 Split long lines in config files
  packages/mesos/extra/mesos.nssm-ssl.j2
  packages/mesos/extra/mesos.nssm.j2
Labels: Ship It

#7188 Change options for default docker app
  packages/dcos-integration-test/extra/test_helpers.py
Labels: Ship It

#7192 logrotate package: update to 3.14.0
  CHANGES.md
  packages/logrotate/buildinfo.json
Labels: merge-by-mergebot

#7173 1.13: Bump Marathon to 1.8.242
  CHANGES.md
  packages/marathon/buildinfo.json
Labels: Ship It

#7199 [master] Automated Bump DC/OS UI v5.0.23
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: merge-by-mergebot

#7180 optimize zookeper calc + enable winpanda for dynamic discovery
  gen/__init__.py
  gen/calc.py
  gen/dcos-config-windows.yaml
  packages/mesos/extra/mesos.nssm-ssl.j2
  packages/mesos/extra/mesos.nssm.j2
  packages/winpanda/extra/src/winpanda/core/cmdconf.py
  packages/winpanda/extra/src/winpanda/core/rc_ctx.py
  packages/winpanda/extra/src/winpanda/tests/unit/test_core_cmdconf.py
  packages/winpanda/extra/src/winpanda/tests/unit/test_core_rc_ctx.py
Labels: Ship It

#7202 Fix escapes in diagnostics test
  packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Labels: merge-by-mergebot

#7210 Update to OpenSSL 1.1.1g
  CHANGES.md
  packages/openssl/buildinfo.json
Labels: merge-by-mergebot

#7203 [1.13] Automated Bump DC/OS UI v4.0.1
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#7184 dcos-net: improve shutdown behavior
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: merge-by-mergebot

#7186 [1.13] dcos-net: improve shutdown behavior
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#7204 [2.0] Automated Bump DC/OS UI v4.0.1
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#7211 [2.0] Update to OpenSSL 1.1.1g
  CHANGES.md
  packages/openssl/buildinfo.json
Labels: Ship It

#7185 [2.0] dcos-net: improve shutdown behavior
  CHANGES.md
  packages/dcos-net/buildinfo.json
Labels: Ship It

#7215 D2IQ-67029: Guarding against exceptions while in ZK lock
  packages/calico/extra/create-calico-docker-network.py
Labels: Ship It

#7212 D2IQ-67223: add 'os' attributes for Linux agents by default
  CHANGES.md
  gen/dcos-config.yaml
Labels: Ship It

#7208 Eliminated 15-minutes hang after completing mesos/mesos-modules cmake.
  packages/mesos-modules/windows.build.ps1
  packages/mesos/windows.build.ps1
Labels: Ship It

#7225 Increase gracePeriodSeconds for test docker app
  packages/dcos-integration-test/extra/test_helpers.py
Labels: Ship It

#7232 Create CHANGES-guidelines.md
  CHANGES-guidelines.md
Labels: merge-by-mergebot

#7238 Update README.md
  README.md
Labels: Ship It
