Repository dcos/dcos, pull requests merged in 2020-11, with the labels that each got.

#7789 Use retry on test_dcos_cni_l4lb as from centos 7.6 first call will fail
  packages/dcos-integration-test/extra/test_networking.py
Labels: Ship It

#7805 calico: fix build
  packages/calico/build
Labels: Ship It

#7814 Restart Docker only if restart file exists
  packages/calico/extra/create-calico-docker-network.py
Labels: Work In Progress

#7815 Restart Docker variation 2
  packages/calico/extra/create-calico-docker-network.py
  packages/calico/extra/dcos-calico-libnetwork-plugin.service
Labels: Ship It

#7769 [WIP] Feat(qualification testing): initial tf files and Makefile targets
  .gitignore
  test-qualification/Makefile
  test-qualification/README.md
  test-qualification/scenarios/centos-7.8.2003/defaults/terraform.tfvars
  test-upgrade/Makefile
  test-upgrade/README.md
  test-upgrade/terraform.tfvars
  test_util/Makefile
  test_util/README.md
  test_util/dcos.mk
  test_util/diagnostics.mk
  test_util/main.tf
  test_util/terraform.mk
  test_util/variables.tf
Labels: Ship It

#7826 [master] Restart Docker if restart file exists
  packages/calico/extra/create-calico-docker-network.py
  packages/calico/extra/dcos-calico-libnetwork-plugin.service
Labels: Ship It

#7825 [2.1] Restart Docker if restart file exists
  packages/calico/extra/create-calico-docker-network.py
  packages/calico/extra/dcos-calico-libnetwork-plugin.service
Labels: Ship It

#7830 Update Mergebot Config for releases 2.2.2, and 2.1.3
  mergebot-config.json
Labels: merge-by-mergebot

#7831 dcos-net: fix argument order for `add_config`
  CHANGES.md
  gen/dcos-config.yaml
  packages/dcos-net/extra/dcos-net-setup.py
Labels: merge-by-mergebot

#7806 [master] Automated Bump DC/OS UI v6.1.19
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: Ship It

#7833 Bump Marathon to 1.11.24
  CHANGES.md
  packages/marathon/buildinfo.json
Labels: Ship It

#7835 [2.1] Bump Marathon to 1.10.36
  CHANGES.md
  packages/marathon/buildinfo.json
Labels: Ship It

#7836 [2.0] Bump Marathon to 1.9.146
  CHANGES.md
  packages/marathon/buildinfo.json
Labels: Ship It

#7848 owners: add jkoelker
  owners.json
Labels: Ship It

#7850 Update Python security libraries
  packages/dcos-integration-test/requirements.txt
  packages/python-certifi/buildinfo.json
  packages/python-cryptography/build
  packages/python-cryptography/buildinfo.json
  test-e2e/requirements.txt
  tox.ini
Labels: Ship It

#7845 etcd: disable etcd when calico is disabled
  CHANGES.md
  gen/dcos-config.yaml
  packages/adminrouter/docker/Dockerfile
  packages/adminrouter/docker/adminrouter-grpc-proxy-etcd.conf
  packages/adminrouter/extra/src/nginx.master.conf
  packages/etcd/extra/systemd/dcos-etcd.service
  test-e2e/test_calico_networking.py
Labels: merge-by-mergebot
