Repository dcos/dcos, pull requests merged in 2020-06, with the labels that each got.

#7322 [master] Remove `os:linux` attribute from public agents
  gen/dcos-config.yaml
Labels: merge-by-mergebot

#7323 [2.1] Remove `os:linux` attribute from public agents
  gen/dcos-config.yaml
Labels: Ship It

#7190 Updated mesos package to use cmake.
  gen/dcos-config.yaml
  packages/mesos-modules/build
  packages/mesos-modules/buildinfo.json
  packages/mesos/build
  packages/mesos/buildinfo.json
Labels: Ship It

#7326 Set 2.1 version to 2.1.0-rc5-dev
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
Labels: merge-by-mergebot

#7332 [2.0] Bump Mesos to 802a50f4902f1f5ca3829dca4a472d8a582f7b9b.
  packages/mesos/buildinfo.json
Labels: Ship It

#7317 Added patch files for DCOS reservation label offer filtering.
  CHANGES.md
  packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
  packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
  packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
  packages/mesos/extra/patches/0004-Revert-Removed-long-ago-deprecated-endpoints.patch
  packages/mesos/extra/patches/0005-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
  packages/mesos/extra/patches/0006-Override-source-address-for-executors.patch
  packages/mesos/extra/patches/0007-Disabled-hostname-validation-for-master-to-scheduler.patch
  packages/mesos/extra/patches/0008-Ensure-framework-labeled-reservations-are-offered-to.patch
  packages/mesos/extra/patches/0009-Added-a-test-for-the-DC-OS-reservation-label-filteri.patch
Labels: merge-by-mergebot

#7277 Update main.tf
  teamcity/main.tf
Labels: Ship It

#7340 Added patch files for DCOS reservation label offer filtering.
  CHANGES.md
  packages/mesos/buildinfo.json
  packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
  packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
  packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
  packages/mesos/extra/patches/0004-Revert-Removed-long-ago-deprecated-endpoints.patch
  packages/mesos/extra/patches/0005-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
  packages/mesos/extra/patches/0006-Override-source-address-for-executors.patch
  packages/mesos/extra/patches/0007-Disabled-hostname-validation-for-master-to-scheduler.patch
  packages/mesos/extra/patches/0008-Ensure-framework-labeled-reservations-are-offered-to.patch
  packages/mesos/extra/patches/0009-Added-a-test-for-the-DC-OS-reservation-label-filteri.patch
Labels: Ship It

#7356 Update 2.1 JIRA Fix Version
  mergebot-config.json
Labels: merge-by-mergebot

#7341 Added patch files for DCOS reservation label offer filtering.
  CHANGES.md
  packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
  packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
  packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
  packages/mesos/extra/patches/0004-Revert-Removed-long-ago-deprecated-endpoints.patch
  packages/mesos/extra/patches/0005-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
  packages/mesos/extra/patches/0006-Override-source-address-for-executors.patch
  packages/mesos/extra/patches/0007-Disabled-hostname-validation-for-master-to-scheduler.patch
  packages/mesos/extra/patches/0008-Ensure-framework-labeled-reservations-are-offered-to.patch
  packages/mesos/extra/patches/0009-Added-a-test-for-the-DC-OS-reservation-label-filteri.patch
Labels: Ship It

#7360 [master] Automated Bump DC/OS UI v5.0.57
  mergebot-config.json
  teamcity/main.tf
Labels: merge-by-mergebot

#7365 2.0.6 dev
  CHANGES.md
  dcos_installer/test_backend.py
  gen/calc.py
Labels: Work In Progress

#7347 Move Telegraf migration into bootstrap script
  packages/bootstrap/extra/dcos_internal_utils/bootstrap.py
  packages/bootstrap/extra/dcos_internal_utils/cli.py
  packages/bootstrap/extra/dcos_internal_utils/utils.py
  packages/bootstrap/extra/pytest.ini
  packages/bootstrap/extra/setup.py
  packages/bootstrap/extra/tests/test_bootstrap.py
  packages/bootstrap/extra/tests/test_cli.py
  packages/telegraf/extra/dcos-telegraf.service
  packages/telegraf/extra/start_telegraf.sh
  packages/telegraf/extra/tools/migrate_containers_dir.sh
Labels: Ship It

#7366 [2.1] Move Telegraf migration into bootstrap script
  CHANGES.md
  packages/bootstrap/extra/dcos_internal_utils/bootstrap.py
  packages/bootstrap/extra/dcos_internal_utils/cli.py
  packages/bootstrap/extra/dcos_internal_utils/utils.py
  packages/bootstrap/extra/pytest.ini
  packages/bootstrap/extra/setup.py
  packages/bootstrap/extra/tests/test_bootstrap.py
  packages/bootstrap/extra/tests/test_cli.py
  packages/telegraf/extra/dcos-telegraf.service
  packages/telegraf/extra/start_telegraf.sh
  packages/telegraf/extra/tools/migrate_containers_dir.sh
Labels: Ship It

#7367 [2.0] Move Telegraf migration into bootstrap script
  CHANGES.md
  packages/bootstrap/extra/dcos_internal_utils/cli.py
  packages/bootstrap/extra/dcos_internal_utils/utils.py
  packages/telegraf/extra/dcos-telegraf.service
  packages/telegraf/extra/start_telegraf.sh
  packages/telegraf/extra/tools/migrate_containers_dir.sh
Labels: Ship It

#7368 [1.13] Move Telegraf migration into bootstrap script
  CHANGES.md
  packages/bootstrap/extra/dcos_internal_utils/cli.py
  packages/bootstrap/extra/dcos_internal_utils/utils.py
  packages/telegraf/extra/dcos-telegraf.service
  packages/telegraf/extra/start_telegraf.sh
  packages/telegraf/extra/tools/migrate_containers_dir.sh
Labels: Ship It

#7370 [master] Automated Bump DC/OS UI v5.1.1
  CHANGES.md
  packages/dcos-ui/buildinfo.json
Labels: merge-by-mergebot

#7384 Reverted back to `single_source` for `mesos` and `mesos-modules` pack…
  packages/mesos-modules/buildinfo.json
  packages/mesos/buildinfo.json
Labels: merge-by-mergebot

#7376 [2.0] Upgrade OpenResty to fix spaces in URLs
  CHANGES.md
  packages/adminrouter/docker/Dockerfile
  packages/adminrouter/extra/src/test-harness/tests/test_master.py
Labels: Ship It

#7375 [2.1] Upgrade OpenResty to fix spaces in URLs
  CHANGES.md
  packages/adminrouter/docker/Dockerfile
  packages/adminrouter/extra/src/test-harness/tests/test_master.py
Labels: Ship It

#7389 [master] Bump Mesos to nightly master a679eb4
  CHANGES.md
  packages/mesos/buildinfo.json
Labels: Ship It

#7361 Upgrade to OpenResty 1.15.8.4
  CHANGES.md
  packages/adminrouter/docker/Dockerfile
  packages/adminrouter/extra/src/test-harness/tests/test_master.py
Labels: Ship It

#7394 Remove vestigial GUI installer port from installer
  gen/build_deploy/bash/dcos_generate_config.sh.in
Labels: merge-by-mergebot

#7395 [2.1] Remove vestigial GUI installer port from installer
  gen/build_deploy/bash/dcos_generate_config.sh.in
Labels: Ship It

#7396 [2.0] Remove vestigial GUI installer port from installer
  gen/build_deploy/bash/dcos_generate_config.sh.in
Labels: Ship It

#7401 [1.13] Bump Mesos to f8b8f1e9c0fbf0a3ee769eebcebf0b4e98e0bfa6.
  packages/mesos/buildinfo.json
Labels: Ship It

#7405 Adjust telegraph configuration
  CHANGES.md
  gen/dcos-config.yaml
Labels: Ship It

#7418 Upgrade to MyPy 0.782
  tox.ini
Labels: merge-by-mergebot

#7419 Update dcos-test-utils
  packages/dcos-integration-test/requirements.txt
  packages/dcos-test-utils/buildinfo.json
Labels: merge-by-mergebot

#7351 2.1: Bump Metronome to 0.6.48
  CHANGES.md
  packages/metronome/buildinfo.json
Labels: Ship It
